config/routes.rb
Eventicator::Application.routes.draw do
  resources :users
  resources :events
  resources :talks
  resources :invitations
  resources :posts
  resources :sessions, only: [:new, :create, :destroy]

  root to: "static_pages#home"

  match '/signup', to: 'users#new'

  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match "/help",  to: "static_pages#help"
  match "/about", to: "static_pages#about"

  match '/calendar(/:year(/:month))' => 'calendar#index',
        as: :calendar,
        constraints: {:year => /\d{4}/, :month => /\d{1,2}/}

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @first_5_events = Event.first_n(5)
    end
  end

  def help
  end

  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About Eventicator</h1>
<p>This is the about page.</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>This is the help page.</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="container">
    <div class="row">
      <div class="span8">
        <div class="news-feed">
          <h1>News <small>The latest info on your favorite projects</small></h1>
          <% if signed_in? %>
            <div class="button-bar">
              <%= link_to new_post_path, class: "btn btn-primary" do %>
                <i class="icon-plus"></i> New Post
              <% end %>
            </div>
          <% end %>
          <%= render Post.limit(5), show_user: true %>
        </div>
      </div>

      <div class="span4">
        <div class="well events-panel">
          <ul class="nav nav-list">
            <li class="nav-header">Upcoming Events
              <div class="management-icons">
                <%= link_to calendar_path do %>
                  <i class="icon-calendar"></i>
                <% end %>
                <%= link_to events_path do %>
                  <i class="icon-list"></i>
                <% end %>
              </div>
            </li>
            <% @first_5_events.each do |event| %>
              <li>
                <%= link_to event do %>
                  <%= event.name %>
                  <small><%= event.start_date.strftime('%B %-d') %></small>
                <% end %>
              </li>
            <% end %>
            <li class="more-link"><a href="<%= events_path %>">more &raquo;</a></li>
          </ul>
        </div>
        <div class="well projects-panel">
          <ul class="nav nav-list">
            <li class="nav-header">My Projects</li>
            <li><a href="#">Great Project</a></li>
            <li><a href="#">Something Else</a></li>
            <li class="more-link"><a href="#">more &raquo;</a></li>
          </ul>
        </div>
        <div class="well teams-panel">
          <ul class="nav nav-list">
            <li class="nav-header">My Teams</li>
            <li><a href="#">Team 1</a></li>
            <li><a href="#">Team 2</a></li>
            <li class="more-link"><a href="#">more &raquo;</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="span8">
      <div class="hero-unit">
        <h1>Welcome to Eventicator!</h1>
        <p>Eventicator is a web site for managing events.  It is especially suited
          for events where multiple teams showcase projects they have made.
        </p>
        <%= link_to "Sign up", signup_path, class: "btn btn-large btn-primary" %>
      </div>
    </div>
    <div class="span4">
      <h3 class="underscored">Already registered?</h3>
      <%= render "sessions/signin" %>
    </div>
  </div>
<% end %>