config/routes.rb
Eventicator::Application.routes.draw do
  resources :users
  resources :events
  resources :talks
  resources :invitations
  resources :posts
  resources :sessions, only: [:new, :create, :destroy]

  root to: "static_pages#home"

  match '/signup', to: 'users#new'

  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match "/help",  to: "static_pages#help"
  match "/about", to: "static_pages#about"

  match '/calendar(/:year(/:month))' => 'calendar#index',
        as: :calendar,
        constraints: {:year => /\d{4}/, :month => /\d{1,2}/}

end

app/models/talk.rb
class Talk < ActiveRecord::Base
  attr_accessible :description, :end_at, :room, :speaker, :start_at, :title
  belongs_to :event

  validates :title,       presence: true, length: { maximum: 100 }
  validates :speaker,     length: { maximum: 50 }
  validates :room,        length: { maximum: 50 }
  validates :description, length: { maximum: 2000 }
  validates :start_at,    presence: true
  validates :end_at,      presence: true, comparison: { on_or_after: :start_at }
  validates :event_id,    presence: true

  validate :must_start_on_or_after_event_start, :must_end_on_or_before_event_end

  default_scope order: 'talks.start_at ASC'

  def must_start_on_or_after_event_start
    if !start_at.nil? && start_at < event.start_date.to_datetime.midnight
      errors.add(:start_at, "can't be before the start of the event")
    end
  end

  def must_end_on_or_before_event_end
    if !end_at.nil? && end_at >= event.end_date.to_datetime.tomorrow.midnight
      errors.add(:end_at, "can't be after the end of the event")
    end
  end
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  before_filter :signed_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_filter :admin_user,     only: [:new, :create, :edit, :update, :destroy]

  def show
    @talk = Talk.find(params[:id])
  end

  def new
    event = Event.find_by_id(params[:event_id])
    if event.nil?
      flash[:error] = "Could not find event #{params[:event_id]}."
      redirect_to root_path
    else
      @talk = event.talks.build
      @talk.start_at = event.start_date.to_datetime.change({hour: 9, minute: 0})
      @talk.end_at = event.start_date.to_datetime.change({hour: 10, minute: 0})
    end
  end

  def create
    event = Event.find_by_id(params[:event_id])
    if event.nil?
      flash[:error] = "Could not find event #{params[:event_id]}."
      redirect_to root_path
    else
      @talk = event.talks.build(params[:talk])
      if @talk.save
        flash[:success] = "Created talk #{@talk.title}."
        redirect_to @talk.event
      else
        render 'new'
      end
    end
  end

  def edit
    @talk = Talk.find(params[:id])
  end

  def update
    @talk = Talk.find(params[:id])
    if @talk.update_attributes(params[:talk])
      flash[:success] = "Talk updated."
      redirect_to @talk
    else
      render 'edit'
    end
  end

  def destroy
    talk = Talk.find(params[:id])
    event = talk.event
    talk.destroy
    redirect_to event, success: "Removed talk #{talk.title}."
  end
end

app/views/talks/_fields.html.erb
<%= f.input :start_at,    as: :string,
                          input_html: { id:    "talk_start_at",
                                        value: @talk.start_at.strftime('%Y-%m-%d %H:%M'),
                                        class: "input-medium" } %>
<%= f.input :end_at,      as: :string,
                          input_html: { id:    "talk_end_at",
                                        value: @talk.end_at.strftime('%Y-%m-%d %H:%M'),
                                        class: "input-medium" } %>
<%= f.input :title,       input_html: { class: "input-xlarge" } %>
<%= f.input :speaker,     input_html: { class: "input-large" } %>
<%= f.input :room,        input_html: { class: "input-large" } %>
<%= f.input :description, input_html: { class: "input-xlarge", rows: 10 } %>

<script type="text/javascript">
  var timepickerOptions = {
    dateFormat: "yy-mm-dd",
    timeFormat: "hh:mm tt",
    minDate:    new Date(<%= @talk.event.start_date.year %>,
                         <%= @talk.event.start_date.month - 1 %>,
                         <%= @talk.event.start_date.day %>,
                         0, 0),
    maxDate:    new Date(<%= @talk.event.end_date.year %>,
                         <%= @talk.event.end_date.month - 1 %>,
                         <%= @talk.event.end_date.day %>,
                         23, 59),
    stepMinute: 5
  };
  $('#talk_start_at').datetimepicker(timepickerOptions);
  $('#talk_end_at').datetimepicker(timepickerOptions);
</script>

app/views/talks/_management_icons.html.erb
<% if signed_in_as_admin? %>
  <div class="management-icons">
    <%= link_to edit_talk_path(talk), id: "edit-talk-#{talk.id}", title: "Edit Talk" do %>
      <i class="icon-pencil"></i>
    <% end %>
    <%= link_to talk,
                method: :delete,
                id: "delete-talk-#{talk.id}",
                title: "Delete Talk",
                data: { confirm: "Are you sure you want to delete this talk?" } do %>
      <i class="icon-trash"></i>
    <% end %>
  </div>
<% end %>

app/views/talks/_talk.html.erb
<div class="event-talk row">
  <div class="start-time span1"><%= talk.start_at.strftime('%H:%M') %></div>
  <div class="details span7">
    <%= link_to talk.title, talk %>
    <% if !(talk.speaker.nil? or talk.speaker.empty?) %>
      by <%= talk.speaker %>
    <% end %>
    <%= render 'talks/management_icons', talk: talk %>
  </div>
</div>

app/views/talks/edit.html.erb
<%= provide(:title, "Edit #{@talk.title}") %>

<div class="row">
  <div class="span8 offset2">
    <h1 class="underscored">Edit <%= @talk.title %></h1>
    <%= simple_form_for(@talk, html: { class: 'form-horizontal' }) do |f| %>
      <%= render 'shared/error_messages', model: @talk %>

      <%= render 'fields', f: f %>

      <div class="form-actions">
        <%= f.submit "Save", class: "btn btn-large btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/talks/new.html.erb
<%= provide(:title, 'New Talk') %>

<div class="row">
  <div class="span8 offset2">
    <h1 class="underscored">New Talk</h1>
    <%= simple_form_for(@talk, html: { class: 'form-horizontal' }) do |f| %>
      <%= render 'shared/error_messages', model: @talk %>

      <%= render 'fields', f: f %>
      <input type="hidden" name="event_id" value="<%= @talk.event_id %>" />

      <div class="form-actions">
        <%= f.submit "Create", class: "btn btn-large btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/talks/show.html.erb
<% provide(:title, "#{@talk.title}") %>
<div class="row">
  <div class="span8">
    &laquo; <%= link_to @talk.event.name, @talk.event %>
    <h1 class="underscored">
      <%= @talk.title %>
      <%= render "management_icons", talk: @talk %>
    </h1>
    <% if !@talk.description.empty? %>
      <div class="talk-description">
        <%= simple_format(@talk.description) %>
      </div>
    <% end %>

    <div>(social buttons here)</div>
  </div>

  <div class="span4">
    <h3 class="underscored">Facts</h3>
    <table class="table table-bordered table-striped">
      <tbody>
        <tr>
          <th>Time</th>
          <td>
            <%= @talk.start_at.strftime('%H:%M') %> -
            <%= @talk.end_at.strftime('%H:%M') %>
            on <%= @talk.start_at.to_date.to_formatted_s(:long) %>
          </td>
        </tr>
        <% if !@talk.speaker.empty? %>
          <tr>
            <th>Speaker</th>
            <td><%= @talk.speaker %></td>
          </tr>
        <% end %>
        <% if !@talk.room.empty? %>
          <tr>
            <th>Room</th>
            <td><%= @talk.room %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>