config/routes.rb
Eventicator::Application.routes.draw do
  resources :users
  resources :events
  resources :talks
  resources :invitations
  resources :posts
  resources :sessions, only: [:new, :create, :destroy]

  root to: "static_pages#home"

  match '/signup', to: 'users#new'

  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match "/help",  to: "static_pages#help"
  match "/about", to: "static_pages#about"

  match '/calendar(/:year(/:month))' => 'calendar#index',
        as: :calendar,
        constraints: {:year => /\d{4}/, :month => /\d{1,2}/}

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :name, :location, :description, :start_date, :end_date

  has_many :talks,                dependent:  :destroy
  has_many :invitations,          dependent:  :destroy
  has_many :accepted_invitations, class_name: "Invitation",
                                  conditions: { accepted: true }
  has_many :accepted_users,       through:    :accepted_invitations,
                                  source:     :invited_user,
                                  uniq:       true

  has_event_calendar start_at_field: 'start_date', end_at_field: 'end_date'

  validates :name,        presence: true, length: { maximum: 100 }
  validates :location,    presence: true, length: { maximum: 250 }
  validates :description, length: { maximum: 2000 }
  validates :start_date,  presence: true
  validates :end_date,    presence: true, comparison: { on_or_after: :start_date }

  def self.first_n(n)
    Event.where('end_date >= ?', Date.today).order('start_date ASC').limit(n)
  end

  def date_range
    DateRange.new(start_date, end_date)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :signed_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_filter :admin_user,     only: [:new, :create, :edit, :update, :destroy]

  def index
    @events = Event.page(params[:page]).order('name ASC')
  end

  def show
    @event = Event.find(params[:id])
    if signed_in? && @event
      invitations = @event.invitations.where(invited_user_id: current_user.id)
      # Highlander (there can be only one).
      if !invitations.empty?
        @invitation = invitations[0]
      end
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(params[:event])
    if @event.save
      flash[:success] = "Created event #{@event.name}."
      redirect_to @event
    else
      render 'new'
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(params[:event])
      flash[:success] = "Event updated."
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    event = Event.find(params[:id])
    event.destroy
    redirect_to events_path, success: "Event deleted."
  end
end

app/views/events/_event.html.erb
<li>
  <%= link_to event.name, event %>
  on <%= event.start_date.to_formatted_s(:long) %>
  at <%= event.location %>
  <%= render "management_icons", event: event %>
</li>

app/views/events/_fields.html.erb
<%= f.input :name,        input_html: { class: "input-xlarge" } %>
<%= f.input :location,    input_html: { class: "input-xlarge", rows: 3 } %>
<%= f.input :description, input_html: { class: "input-xlarge", rows: 10 } %>
<%= f.input :start_date,  as: :string, input_html: { class: "input-small date-field" } %>
<%= f.input :end_date,    as: :string, input_html: { class: "input-small date-field" } %>

app/views/events/_invitation.html.erb
<% if !@invitation.nil? %>
  <div class="event-invitation">
    <% if @invitation.accepted.nil? %>
      <div class="invitation-question">
        Would you like to accept the invitation from
        <%= @invitation.inviting_user.name %>?
        <div class="invitation-response-button">
          <%= form_for(@invitation, url: invitation_path(@invitation.token)) do |f| %>
            <input type="hidden" name="invitation[accepted]" value="true" />
            <input type="submit" value="Accept" class="btn btn-success" />
          <% end %>
        </div>
        <div class="invitation-response-button">
          <%= form_for(@invitation, url: invitation_path(@invitation.token)) do |f| %>
            <input type="hidden" name="invitation[accepted]" value="false" />
            <input type="submit" value="Decline" class="btn btn-danger" />
          <% end %>
        </div>
      </div>
    <% else %>
      <% if @invitation.accepted? %>
        <i class="icon-ok-sign"></i> I plan to attend.
      <% else %>
        <i class="icon-remove-sign"></i> I do not plan to attend.
      <% end %>
      <%= render 'invite_friends' %>
    <% end %>
  </div>
<% else %>
  <% if signed_in? %>
    <!--
    FIXME: Why isn't this outputting the hidden fields correctly?
    <%= form_for(@event.invitations.build(inviting_user_id: current_user.id,
                                          invited_user_id:  current_user.id,
                                          accepted:         true)) do |f| %>
      <input type="hidden" name="event_id" value="<%= @event.id %>" />
      <% f.hidden_field :inviting_user_id %>
      <% f.hidden_field :invited_user_id %>
      <% f.hidden_field :accepted %>
      <% f.submit "Register", class: "btn btn-large btn-primary" %>
    <% end %>
    -->
    <div class="event-registration">
      <div class="invitation-response-button">
        <%= form_for(@event.invitations.build(inviting_user_id: current_user.id,
                                              invited_user_id:  current_user.id,
                                              accepted:         true)) do |f| %>
          <input type="hidden" name="event_id" value="<%= @event.id %>" />
          <input type="hidden" name="invitation[inviting_user_id]"
                 value="<%= current_user.id %>" />
          <input type="hidden" name="invitation[invited_user_id]"
                 value="<%= current_user.id %>" />
          <input type="hidden" name="invitation[accepted]" value="true" />
          <input type="submit" name="commit" value="Register"
                 class="btn btn-large btn-primary" />
        <% end %>
      </div>
      <%= render 'invite_friends' %>
    </div>
  <% end %>
<% end %>

app/views/events/_invite_friends.html.erb
<div class="invitation-response-button">
  <%= link_to "Invite Friends",
              "#{new_invitation_path}?event_id=#{@event.id}",
              class: "btn btn-large btn-primary" %>
</div>

app/views/events/_management_icons.html.erb
<% if signed_in_as_admin? %>
  <div class="management-icons">
    <%= link_to edit_event_path(event), id: "edit-event-#{event.id}", title: "Edit Event" do %>
      <i class="icon-pencil"></i>
    <% end %>
    <%= link_to event,
                method: :delete,
                id: "delete-event-#{event.id}",
                title: "Delete Event",
                data: { confirm: "Are you sure you want to delete this event?" } do %>
      <i class="icon-trash"></i>
    <% end %>
  </div>
<% end %>

app/views/events/edit.html.erb
<%= provide(:title, "Edit #{@event.name}") %>

<div class="row">
  <div class="span8 offset2">
    <h1 class="underscored">Edit <%= @event.name %></h1>
    <%= simple_form_for(@event, html: { class: 'form-horizontal' }) do |f| %>
      <%= render 'shared/error_messages', model: @event %>

      <%= render 'fields', f: f %>

      <div class="form-actions">
        <%= f.submit "Save", class: "btn btn-large btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<%= provide(:title, 'All events') %>
<h1 class="underscored">All events</h1>

<div class="button-bar">
  <%= link_to calendar_path, class: "btn" do %>
    <i class="icon-calendar"></i> Calendar 
  <% end %>
  <% if signed_in_as_admin? %>
    <%= link_to new_event_path, class: "btn" do %>
      <i class="icon-plus"></i> New Event
    <% end %>
  <% end %>
</div>

<%= will_paginate %>

<ul class="events">
  <%= render @events %>
</ul>

<%= will_paginate %>

app/views/events/new.html.erb
<%= provide(:title, 'New Event') %>

<div class="row">
  <div class="span8 offset2">
    <h1 class="underscored">New Event</h1>
    <%= simple_form_for(@event, html: { class: 'form-horizontal' }) do |f| %>
      <%= render 'shared/error_messages', model: @event %>

      <%= render 'fields', f: f %>

      <div class="form-actions">
        <%= f.submit "Create", class: "btn btn-large btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<% provide(:title, "#{@event.name}") %>
<div class="row">
  <div class="span8">
    <div class="hero-unit">
      <h1>
        <%= @event.name %>
        <%= render "management_icons", event: @event %>
      </h1>
      <p class="event-dates"><%= @event.date_range.to_s %></p>
      <div class="event-description">
        <%= simple_format(@event.description) %>
      </div>
      <div>(social buttons here)</div>
      <%= render 'invitation' %>
    </div>

    <% if @event.talks.any? || signed_in_as_admin? %>
      <h2 class="underscored">Agenda</h2>
      <% if signed_in_as_admin? %>
        <div class="button-bar">
          <%= link_to "#{new_talk_path}?event_id=#{@event.id}", class: 'btn' do %>
            <i class="icon-plus"></i> Add Talk
          <% end %>
        </div>
      <% end %>
      <!-- FIXME: Separate by day. -->
      <%= render @event.talks %>
    <% end %>
  </div>

  <div class="span4">
    <h3 class="underscored">Location</h3>
    <div class="event-location">
      <%= simple_format(@event.location) %>
    </div>
    <div class="event-map">
      <%= map_for(@event.location) %>
    </div>
    <h3 class="underscored">Registered</h3>
    <div class="event-registered-users">
      <% @event.accepted_users.order('updated_at DESC').limit(30).each do |accepted_user| %>
        <%= link_to accepted_user do %><%= gravatar_for(accepted_user, size: 32) %><% end %>
      <% end %>
    </div>
  </div>
</div>