config/routes.rb
Eventicator::Application.routes.draw do
  resources :users
  resources :events
  resources :talks
  resources :invitations
  resources :posts
  resources :sessions, only: [:new, :create, :destroy]

  root to: "static_pages#home"

  match '/signup', to: 'users#new'

  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match "/help",  to: "static_pages#help"
  match "/about", to: "static_pages#about"

  match '/calendar(/:year(/:month))' => 'calendar#index',
        as: :calendar,
        constraints: {:year => /\d{4}/, :month => /\d{1,2}/}

end

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/"><%= image_tag("EventicatorLogo.png", alt: "eventicator") %></a>
      <div class="nav-collapse">
        <ul class="nav pull-right">
          <li><%= link_to "Home",  root_path %></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Help",  help_path  %></li>
          <% if signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile",  current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title(yield(:title)) %></title>
    <link href='http://fonts.googleapis.com/css?family=Lato:400,700,400italic' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div id="content">
      <div class="container">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>">
            <a class="close" data-dismiss="alert" href="#">&times;</a>
            <%= value %>
          </div>
        <% end %>
        <%= yield %>
        <div class="footer">
          <p>Copyright (c) 2012 Eric Galluzzo.  Some rights reserved.</p>
        </div>
        <% if Rails.env.development? %>
          <div class="accordion-group">
            <div class="accordion-heading">
              <a class="accordion-toggle" data-toggle="collapse" href="#debug-info">
                Debugging Information
              </a>
            </div>
            <div id="debug-info" class="accordion-body collapse">
              <div class="accordion-inner">
                <%= debug(params) %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </body>
</html>